language: php

php:
  - 5.5
  - 5.6
  - 7

matrix:
  allow_failures:
    - php: 7

before_script:
  - echo "extension = zmq.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer update

script:
  - php ./vendor/bin/phpunit --configuration=phpunit.dist.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
